version: "3.8"

services:

  fcitx5-prebuilder-base:
    image: fcitx5-prebuilder-base:latest
    build:
      context: .
      dockerfile: Dockerfile-base

  fcitx5-prebuilder:
    image: fcitx5-prebuilder:latest
    container_name: fcitx5-prebuilder
    entrypoint: tail -f /dev/null
    build:
      context: .
      dockerfile: Dockerfile