FROM ubuntu:24.04

RUN sed -i -E 's/(archive|security).ubuntu.com/mirrors.tuna.tsinghua.edu.cn/g' /etc/apt/sources.list.d/ubuntu.sources

RUN ulimit -n 10240
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y git curl wget tar ca-certificates build-essential cmake extra-cmake-modules pkg-config \
    libxcb1-dev libxcb-keysyms1-dev libxcb-util0-dev libdbus-1-dev libevent-dev uuid-dev gettext \
    libsystemd-dev libxkbfile-dev libxkbcommon-x11-dev libxcb-xkb-dev libxcb1-dev libpango1.0-dev \
    libpangocairo-1.0-0 libenchant-2-dev libxcb-ewmh-dev libxcb-xinerama0-dev libxcb-icccm4-dev \
    libxcb-ewmh-dev wayland-protocols libboost-dev libcurl4-gnutls-dev libopencc-dev qtbase5-dev \
    libqt5webchannel5-dev libboost-iostreams-dev gobject-introspection libgirepository1.0-dev \
    libgtk2.0-dev libgtk-3-dev libfmt-dev libxcb-randr0-dev libxcb-shape0-dev libxcb-xfixes0-dev \
    libjson-c-dev iso-codes libzstd-dev libboost-filesystem-dev libgtk-4-dev qtbase5-private-dev \
    fcitx5-module-lua-dev libqt5webkit5-dev liblua5.3-dev qtwebengine5-dev iso-codes libasio-dev \
    binutils-x86-64-linux-gnu binutils-aarch64-linux-gnu binutils-arm-linux-gnueabihf binutils-i686-linux-gnu \
    meson libxml2-dev libgmp-dev gperf zstd

RUN curl --proto '=https' --tlsv1.2 -sSf https://get-ghcup.haskell.org | sh

ENV PATH=/root/.cabal/bin:/root/.ghcup/bin:/usr/bin:/usr/sbin:/usr/local/bin

# fix libime copy file error
ENV LANG=zh_CN.UTF-8
ENV LC_ALL=zh_CN.UTF-8

RUN apt-get install -y locales language-pack-zh-hans fonts-wqy-zenhei && \
    sed -i '/zh_CN.UTF-8/s/^# //g' /etc/locale.gen && \
    locale-gen && \
    update-locale LANG=zh_CN.UTF-8

WORKDIR /prebuilder

COPY . .

RUN ./build-cabal
